In [121]:
#!pip install -r requirements.txt
import numpy as np 
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [122]:
f = "data/tcga_brca_all_clean.csv.zip"

#TODO slide_id -> file path 

## Preprocessing genomic data 

In [162]:
n_bins = 4
df = pd.read_csv(f,compression='zip')

df_uncensored = (df[df["censorship"]==0]).drop_duplicates(["case_id"])
_,bins = pd.qcut(df_uncensored['survival_months'],q = n_bins,retbins=True)  # distribute censored survival months into quartiles

# adapt bins 
bins[0] = 0 
bins[-1] = np.inf
#
labels=[i for i in range(n_bins)]
labels

df.insert(6,"survival_months_discretized",  pd.cut(df["survival_months"],
                                                               bins=bins, 
                                                               labels=labels)) # insert binned survival momnth 
k = 7
df.insert(3,"kfold",df.index%k) # insert kfold 
df.head(5)

case_id                                           slide_id site  \
0  TCGA-3C-AALI  TCGA-3C-AALI-01Z-00-DX1.F6E9A5DF-D8FB-45CF-B4B...   3C   
1  TCGA-3C-AALI  TCGA-3C-AALI-01Z-00-DX2.CF4496E0-AB52-4F3E-BDF...   3C   
2  TCGA-3C-AALJ  TCGA-3C-AALJ-01Z-00-DX1.777C0957-255A-42F0-9EE...   3C   
3  TCGA-3C-AALJ  TCGA-3C-AALJ-01Z-00-DX2.62DFE56B-B84C-40F9-962...   3C   
4  TCGA-3C-AALK  TCGA-3C-AALK-01Z-00-DX1.4E6EB156-BB19-410F-878...   3C   

   is_female oncotree_code   age survival_months_discretized  survival_months  \
0        1.0           IDC  50.0                           3           131.57   
1        1.0           IDC  50.0                           3           131.57   
2        1.0           IDC  62.0                           2            48.42   
3        1.0           IDC  62.0                           2            48.42   
4        1.0           IDC  52.0                           2            47.57   

   censorship  train  ...  ZWINT_rnaseq  ZXDA_rnaseq  ZXDB_rnaseq  \
0         1.0    1.0  ...        0.3196      -0.1816      -0.4114   
1         1.0    1.0  ...        0.3196      -0.1816      -0.4114   
2         1.0    1.0  ...        3.2911      -1.1222      -0.1302   
3         1.0    1.0  ...        3.2911      -1.1222      -0.1302   
4         1.0    1.0  ...       -0.2431      -0.3657      -0.4472   

   ZXDC_rnaseq  ZYG11A_rnaseq  ZYG11B_rnaseq  ZYX_rnaseq  ZZEF1_rnaseq  \
0       1.0797         1.0743        -1.0477      0.9689       -0.3256   
1       1.0797         1.0743        -1.0477      0.9689       -0.3256   
2      -1.4793         2.5267        -1.3026      0.9433       -1.1210   
3      -1.4793         2.5267        -1.3026      0.9433       -1.1210   
4      -1.0557         0.8232        -1.0342      1.0729       -1.4634   

   ZZZ3_rnaseq  TPTEP1_rnaseq  
0      -1.1244         2.4038  
1      -1.1244         2.4038  
2      -0.9310        -0.6472  
3      -0.9310        -0.6472  
4      -0.5710        -0.5402  

[5 rows x 20981 columns]

scale genomic data first and store in DF again
then add labels to stratify 

In [165]:
# todo add new column k-th-fold that contains an int in arange(k) where k is a cluster 
groundtruth = df["survival_months_discretized"]
censorship = df["censorship"]
genomics = df[df.keys()[11:]]
genomics


NOTCH2_cnv  ACP6_cnv  ANKRD20A12P_cnv  ANKRD34A_cnv  ANKRD35_cnv  \
403           1         1                1             1            1   
598           0         0                0             0            0   
817           0         0                0             0            0   
244           0         0                0             0            0   
320           1         1                1             1            1   
..          ...       ...              ...           ...          ...   
767           1         1                1             1            1   
72            1         1                1             1            1   
908           0         0                0             0            0   
235           1         1                1             1            1   
37           -1         1                1             1            1   

     BCL9_cnv  BOLA1_cnv  CD160_cnv  CHD1L_cnv  FAM72B_cnv  ...  ZWINT_rnaseq  \
403         1          1          1          1           1  ...       -0.6752   
598         0          0          0          0           0  ...       -0.0525   
817         0          0          0          0           0  ...        0.3245   
244         0          0          0          0           0  ...       -0.9956   
320         1          1          1          1           1  ...        1.2331   
..        ...        ...        ...        ...         ...  ...           ...   
767         1          1          1          1           1  ...       -0.2865   
72          1          1          1          1           1  ...       -0.2171   
908         0          0          0          0           0  ...       -0.5362   
235         1          1          1          1           1  ...       -0.9187   
37          1          1          1          1           1  ...       -1.0144   

     ZXDA_rnaseq  ZXDB_rnaseq  ZXDC_rnaseq  ZYG11A_rnaseq  ZYG11B_rnaseq  \
403      -0.6708      -0.6352       0.3693         0.1446         3.2597   
598      -0.2132      -0.2256       0.1374         0.5972        -0.7959   
817      -0.3567       1.7451      -0.5448         1.7019        -0.6458   
244      -0.5694      -0.7817       0.0144        -0.9142        -1.2975   
320       0.9744      -0.6189      -2.1771         1.8906        -0.3966   
..           ...          ...          ...            ...            ...   
767      -0.7057      -0.8934       0.2821        -0.1644        -1.1582   
72        0.1621      -0.3724       1.5166         0.5926         1.0383   
908       0.3350       0.2731       1.8174         0.8894         0.7809   
235       0.9464       0.0057       0.2020         0.0415        -0.1023   
37       -1.0623      -0.2870      -1.3374        -0.1074        -1.3805   

     ZYX_rnaseq  ZZEF1_rnaseq  ZZZ3_rnaseq  TPTEP1_rnaseq  
403     -0.1603       -0.8919       0.5903        -0.0801  
598     -1.1744       -0.3666      -1.3888        -0.7535  
817      2.4399        0.7366      -0.3115         0.9021  
244      3.6863        0.0938      -0.0315         0.0677  
320     -0.0656       -1.6399      -0.5391        -0.6042  
..          ...           ...          ...            ...  
767      0.1480        0.0373      -0.6824        -0.5994  
72       0.0326       -0.1507       0.2853        -0.3509  
908     -0.6663       -0.3758       0.2849        -0.6437  
235      0.4811        0.3689       0.0824        -0.4666  
37       0.3683       -0.8526      -1.0761         0.8115  

[1023 rows x 20971 columns]

In [169]:


scaler = StandardScaler()
scaled_genomics = scaler.fit_transform(genomics)
#scaler.inverse_transform(scaled_genomics)
df_scaled = df.copy()
df_scaled[df.keys()[11:]] = scaled_genomics



###  This leads to the full function:

In [123]:
def clean2trainable(df_path,k,n_bins=4,savename = None):
    df = pd.read_csv(df_path,compression='zip')

    # get time bins 
    df_uncensored = (df[df["censorship"]==0]).drop_duplicates(["case_id"])
    _,bins = pd.qcut(df_uncensored['survival_months'],q = n_bins,retbins=True)  # distribute censored survival months into quartiles

    # adapt time bins 
    bins[0] = 0 
    bins[-1] = np.inf
    # bin name = index 
    labels = [i for i in range(n_bins)]
    df.insert(6,"survival_months_discretized",  pd.cut(df["survival_months"],
                                                               bins=bins, 
                                                               labels=labels)) # insert binned survival month 
    df.insert(3,"kfold",df.index%k) # insert kfold 

    genomics = df[df.keys()[11:]]

    scaler = StandardScaler()
    scaled_genomics = scaler.fit_transform(genomics)
    df[df.keys()[11:]] = scaled_genomics

    if savename is not None:
        df.to_csv(savename,index=False)
    return df 

In [124]:
f = "data/tcga_brca_all_clean.csv.zip"
new_df = clean2trainable(f,5,4,savename = "./data/tcga_brca_trainable.csv")
#new_df = clean2trainable(f,7,4)

In [125]:
f_new = "data/tcga_brca_trainable.csv"
df = pd.read_csv(f_new)
df.head()

case_id                                           slide_id site  \
0  TCGA-3C-AALI  TCGA-3C-AALI-01Z-00-DX1.F6E9A5DF-D8FB-45CF-B4B...   3C   
1  TCGA-3C-AALI  TCGA-3C-AALI-01Z-00-DX2.CF4496E0-AB52-4F3E-BDF...   3C   
2  TCGA-3C-AALJ  TCGA-3C-AALJ-01Z-00-DX1.777C0957-255A-42F0-9EE...   3C   
3  TCGA-3C-AALJ  TCGA-3C-AALJ-01Z-00-DX2.62DFE56B-B84C-40F9-962...   3C   
4  TCGA-3C-AALK  TCGA-3C-AALK-01Z-00-DX1.4E6EB156-BB19-410F-878...   3C   

   kfold  is_female oncotree_code   age  survival_months_discretized  \
0      0        1.0           IDC  50.0                            3   
1      1        1.0           IDC  50.0                            3   
2      2        1.0           IDC  62.0                            2   
3      3        1.0           IDC  62.0                            2   
4      4        1.0           IDC  52.0                            2   

   survival_months  censorship  ...  ZWINT_rnaseq  ZXDA_rnaseq  ZXDB_rnaseq  \
0           131.57         1.0  ...      0.153655    -0.207313    -0.427975   
1           131.57         1.0  ...      0.153655    -0.207313    -0.427975   
2            48.42         1.0  ...      2.665836    -1.099110    -0.184212   
3            48.42         1.0  ...      2.665836    -1.099110    -0.184212   
4            47.57         1.0  ...     -0.322065    -0.381861    -0.459009   

   ZXDC_rnaseq  ZYG11A_rnaseq  ZYG11B_rnaseq  ZYX_rnaseq  ZZEF1_rnaseq  \
0     0.825128       0.825317      -0.963470    0.880672      0.164444   
1     0.825128       0.825317      -0.963470    0.880672      0.164444   
2    -1.279398       2.112450      -1.190473    0.856429     -0.579342   
3    -1.279398       2.112450      -1.190473    0.856429     -0.579342   
4    -0.931029       0.602789      -0.951448    0.979160     -0.899523   

   ZZZ3_rnaseq  TPTEP1_rnaseq  
0    -1.064402       2.395788  
1    -1.064402       2.395788  
2    -0.874345      -0.485389  
3    -0.874345      -0.485389  
4    -0.520568      -0.384345  

[5 rows x 20982 columns]

In [127]:
df[df.keys()[11:]].head()

NOTCH2_cnv  ACP6_cnv  ANKRD20A12P_cnv  ANKRD34A_cnv  ANKRD35_cnv  BCL9_cnv  \
0   -2.117218 -2.241841        -2.241841     -2.241841    -2.241841 -2.241841   
1   -2.117218 -2.241841        -2.241841     -2.241841    -2.241841 -2.241841   
2   -0.863795 -0.929074        -0.929074     -0.929074    -0.929074 -0.929074   
3   -0.863795 -0.929074        -0.929074     -0.929074    -0.929074 -0.929074   
4   -0.863795 -0.929074        -0.929074     -0.929074    -0.929074 -0.929074   

   BOLA1_cnv  CD160_cnv  CHD1L_cnv  FAM72B_cnv  ...  ZWINT_rnaseq  \
0  -2.241841  -2.241841  -2.241841   -2.241841  ...      0.153655   
1  -2.241841  -2.241841  -2.241841   -2.241841  ...      0.153655   
2  -0.929074  -0.929074  -0.929074   -0.929074  ...      2.665836   
3  -0.929074  -0.929074  -0.929074   -0.929074  ...      2.665836   
4  -0.929074  -0.929074  -0.929074   -0.929074  ...     -0.322065   

   ZXDA_rnaseq  ZXDB_rnaseq  ZXDC_rnaseq  ZYG11A_rnaseq  ZYG11B_rnaseq  \
0    -0.207313    -0.427975     0.825128       0.825317      -0.963470   
1    -0.207313    -0.427975     0.825128       0.825317      -0.963470   
2    -1.099110    -0.184212    -1.279398       2.112450      -1.190473   
3    -1.099110    -0.184212    -1.279398       2.112450      -1.190473   
4    -0.381861    -0.459009    -0.931029       0.602789      -0.951448   

   ZYX_rnaseq  ZZEF1_rnaseq  ZZZ3_rnaseq  TPTEP1_rnaseq  
0    0.880672      0.164444    -1.064402       2.395788  
1    0.880672      0.164444    -1.064402       2.395788  
2    0.856429     -0.579342    -0.874345      -0.485389  
3    0.856429     -0.579342    -0.874345      -0.485389  
4    0.979160     -0.899523    -0.520568      -0.384345  

[5 rows x 20971 columns]

## k-Fold crossvalidation
1. Cluster dataset into k groups (shuffle first(seeded) then stratify by patient,split into equal chunks)
2. use one group for testing and the others for training
3. rotate such that each group is once used for testing
4. use distribution of testing results to estimate real value 



In [13]:
k = 7 
a = np.arange(k) # df k-th fold 
for i in range(k):  
    a = (a+1)%k
    print(f"train on {a[:-1]} test on {a[-1]}, store results in foldername: experiment1_fold{a[-1]}")



train on [1 2 3 4 5 6] test on 0, store results in foldername: experiment1_fold0
train on [2 3 4 5 6 0] test on 1, store results in foldername: experiment1_fold1
train on [3 4 5 6 0 1] test on 2, store results in foldername: experiment1_fold2
train on [4 5 6 0 1 2] test on 3, store results in foldername: experiment1_fold3
train on [5 6 0 1 2 3] test on 4, store results in foldername: experiment1_fold4
train on [6 0 1 2 3 4] test on 5, store results in foldername: experiment1_fold5
train on [0 1 2 3 4 5] test on 6, store results in foldername: experiment1_fold6


In [24]:
df = pd.DataFrame({"col1": np.arange(100),"col2":np.random.rand(100)})
df
df["col1"] = df["col1"].apply(lambda x: f"thisis{x}")
df

col1      col2
0    thisis0  0.771627
1    thisis1  0.445847
2    thisis2  0.593957
3    thisis3  0.457410
4    thisis4  0.182458
..       ...       ...
95  thisis95  0.087985
96  thisis96  0.931732
97  thisis97  0.929314
98  thisis98  0.755483
99  thisis99  0.349347

[100 rows x 2 columns]

In [28]:
f = "data/tcga_brca_all_clean.csv.zip"
f = f.replace("all_clean.csv.zip","trainable.csv")
f

'data/tcga_brca_trainable.csv'

In [29]:
!pip install torchmetrics


  Using cached torchmetrics-0.11.4-py3-none-any.whl (519 kB)

[notice] A new release of pip available: 22.2.2 -> 23.1.2
[notice] To update, run: pip install --upgrade pip


In [58]:
import torch 
idx = torch.randint(low=0,high=4,size=(100,))
values = torch.zeros(size=(100,4))
source = torch.ones(size=(100,))

In [59]:
values.scatter_(dim=1,index=idx,src=source)

RuntimeError: Index tensor must have the same number of dimensions as self tensor

In [104]:
groundtruth = torch.zeros(size=(10,4))
a,b = groundtruth.size()
labels = torch.randint(low=0,high=b,size=(1,a))
groundtruth[torch.arange(a),labels]=1
groundtruth

tensor([[0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]])

In [105]:
from torchmetrics import Accuracy
acc = Accuracy("multiclass")

tensor([[1, 1, 1, 0, 0, 1, 2, 2, 3, 3]])

In [112]:
a = torch.randint(low=0,high=2,size=(100,))
a



tensor([1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
        0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
        0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 1])

In [120]:

from sksurv.metrics import concordance_index_censored
c = torch.randint(0,2,size=(100,))
l = torch.randint(0,4,size=(100,))
out = nn.Sigmoid()(torch.rand(size=(100,4)))
c_index = concordance_index_censored(c,l,out)


ValueError: Expected 1D array, got 2D array instead:
array=[[0.7033437  0.5068377  0.654999   0.5990905 ]
 [0.7150219  0.599375   0.7102213  0.669106  ]
 [0.64452285 0.5671275  0.71529394 0.6757698 ]
 [0.6388677  0.62970865 0.64201355 0.5307401 ]
 [0.60350907 0.72728115 0.53220797 0.518223  ]
 [0.68350834 0.6934904  0.5089255  0.61560374]
 [0.67109674 0.6994699  0.6647645  0.52406156]
 [0.55831575 0.64931524 0.5347419  0.65587   ]
 [0.52917504 0.6606084  0.55667764 0.65744233]
 [0.7292093  0.56855935 0.7007709  0.66647863]
 [0.6349134  0.6343174  0.57802343 0.67564833]
 [0.6474086  0.58789873 0.6473337  0.5406985 ]
 [0.6528097  0.55204225 0.5219494  0.588915  ]
 [0.5066584  0.575144   0.62465805 0.5473152 ]
 [0.6980143  0.5550397  0.69929653 0.67663085]
 [0.66518444 0.5020233  0.54762226 0.68529356]
 [0.61191684 0.57054913 0.51956755 0.5036999 ]
 [0.5990251  0.6647159  0.5022067  0.6415785 ]
 [0.5096261  0.5296232  0.64971465 0.5950778 ]
 [0.7218662  0.65232795 0.5983458  0.6257463 ]
 [0.65301895 0.6039311  0.57282114 0.64343935]
 [0.70950943 0.5643408  0.71161604 0.5036222 ]
 [0.56625646 0.509335   0.5792254  0.61572915]
 [0.62246877 0.59285855 0.5865239  0.6409882 ]
 [0.5512244  0.5397312  0.58580446 0.594414  ]
 [0.6483152  0.6868134  0.65667236 0.5230461 ]
 [0.5616211  0.698877   0.63359326 0.728736  ]
 [0.6529768  0.6710834  0.666662   0.52926576]
 [0.5455406  0.5901774  0.5039173  0.50229514]
 [0.6278486  0.72436374 0.6860912  0.6959076 ]
 [0.50597304 0.713814   0.6326286  0.6273644 ]
 [0.65662265 0.5647073  0.58616865 0.646891  ]
 [0.6678679  0.55246246 0.5616041  0.71274585]
 [0.5203591  0.5386698  0.64613324 0.61203194]
 [0.68008655 0.6873198  0.71844333 0.6257025 ]
 [0.7298277  0.67418826 0.5938301  0.66317636]
 [0.67543834 0.5023487  0.6053202  0.6490979 ]
 [0.67269105 0.6210878  0.71898174 0.66912603]
 [0.70456284 0.71981895 0.66602397 0.64326096]
 [0.60190856 0.51107204 0.5898658  0.61134875]
 [0.59263074 0.5784401  0.54741335 0.5614796 ]
 [0.5989356  0.55273384 0.5732944  0.71651936]
 [0.5913896  0.54938984 0.60361534 0.53534436]
 [0.5141062  0.6119989  0.54016924 0.6341148 ]
 [0.71425146 0.6726476  0.58939916 0.7245826 ]
 [0.5873254  0.59445065 0.58369744 0.5891026 ]
 [0.5968411  0.64003295 0.6959099  0.6444287 ]
 [0.5450495  0.53397685 0.62487507 0.5077089 ]
 [0.5835435  0.6215533  0.57735515 0.642489  ]
 [0.557307   0.56761986 0.70220196 0.51394594]
 [0.5159483  0.7038531  0.6261901  0.63434386]
 [0.72761047 0.6025582  0.70891714 0.61075985]
 [0.5199391  0.50275004 0.59646523 0.66402894]
 [0.6963825  0.5442542  0.567837   0.70562667]
 [0.6432466  0.62537783 0.63242483 0.57596123]
 [0.5894853  0.66055566 0.65344256 0.5931886 ]
 [0.7301526  0.50607795 0.5494923  0.6291933 ]
 [0.7089705  0.6961766  0.5586037  0.5976287 ]
 [0.6130313  0.5604356  0.5972878  0.68639934]
 [0.51664704 0.68900746 0.68184733 0.53696966]
 [0.5886826  0.55988073 0.70646673 0.70089626]
 [0.54090255 0.7026498  0.55707085 0.54038   ]
 [0.5840731  0.67154956 0.5217902  0.5183401 ]
 [0.65526056 0.7000793  0.6698624  0.5305141 ]
 [0.63102967 0.60221153 0.55749315 0.59235895]
 [0.608334   0.707181   0.507087   0.6083674 ]
 [0.515192   0.5415555  0.5845034  0.582528  ]
 [0.62123877 0.5697925  0.5561974  0.5007077 ]
 [0.61007625 0.70058566 0.62560135 0.6279507 ]
 [0.7283216  0.56833994 0.72932595 0.59095794]
 [0.68331707 0.66165876 0.61356664 0.5835217 ]
 [0.5145504  0.5252778  0.6049514  0.53632414]
 [0.5843128  0.51487863 0.541528   0.6749439 ]
 [0.651314   0.525107   0.530047   0.57662064]
 [0.5899187  0.72903425 0.58088046 0.56718   ]
 [0.59032536 0.6409243  0.52353984 0.65532184]
 [0.6856491  0.5704291  0.6997388  0.5607072 ]
 [0.5616982  0.56394184 0.7009696  0.58921385]
 [0.6050089  0.65880936 0.7154291  0.72521573]
 [0.6253197  0.6155239  0.6816433  0.6848565 ]
 [0.5421478  0.5141121  0.6021258  0.58528125]
 [0.5093989  0.56185734 0.6934937  0.6141861 ]
 [0.626201   0.6440658  0.5739234  0.58163154]
 [0.516708   0.5852681  0.54061425 0.6389016 ]
 [0.60063165 0.71721005 0.6172488  0.5289654 ]
 [0.69206935 0.68975365 0.54912287 0.6318212 ]
 [0.5011444  0.61085147 0.69184405 0.5598021 ]
 [0.73076046 0.61929005 0.6955243  0.5656313 ]
 [0.69410634 0.72007406 0.5879938  0.6407076 ]
 [0.6469488  0.60425884 0.5105472  0.5041881 ]
 [0.69766206 0.6466432  0.6021804  0.5660987 ]
 [0.69878095 0.59292924 0.67088234 0.52607673]
 [0.6836516  0.6855315  0.54005367 0.52829343]
 [0.7178681  0.6848087  0.65245676 0.609253  ]
 [0.5492158  0.55435956 0.56264997 0.5188395 ]
 [0.63143706 0.6213038  0.5782583  0.69672054]
 [0.5931135  0.51481485 0.5317573  0.6294442 ]
 [0.6040276  0.5475191  0.65634286 0.6323826 ]
 [0.6253122  0.66581166 0.5658497  0.60413456]
 [0.5506321  0.5837093  0.7030357  0.5361747 ]].
